### ISSUE TITLE
Error in creating multi-column indexes from JSON

### ISSUE THREAD

**Issue by saystone** [strongloop/loopback-connector-mysql#80]
Hello!

```
// tag-map.json
{
  "name": "TagMap",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "fripId": {
      "type": "number",
      "required": true
    },
    "tagId": {
      "type": "number",
      "required": true
    }
  },
  "indexes": {
    "fripId_tagId_index": {
      "keys": {
        "fripId": 1,
        "tagId": 1
      }
    }
  },
...relations, acls, ...
}
```
```
// autoupdate.js
var app = require('./server');
var dataSource = app.dataSources.db;
dataSource.autoupdate(['TagMap'], function(err) {
  if (err) {
    throw err;
  } else {
    dataSource.disconnect();
  }
});
```
```
$ node ./server/autoupdate.js
```
It throws following error:
```
Error: ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'undefined' doesn't exist in table
```
So i'm trying to logging query:
```
ALTER TABLE `TagMap` ADD  INDEX  `fripId_tagId_index` (undefined)
```
I referenced this documentation:
http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file
But this code seems to be different:
https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L884-L904

**Comment by wrensburg** [comment]
Found so many bugs with indexes and mysql. For this specific use case, I found a work around (not documented). Convert your`indexes` property above to use `columns`, rather than `keys`, like this..

```
"indexes": {
    "fripId_tagId_index": {
      "columns": "fripId, tagId"
    }
  }
```

**Comment by saystone** [comment]
@wrensburg it works. thanks!

**Comment by sgilligan** [comment]
+1

**Comment by superkhau** [comment]
@saystone Has this been resolved? Can I close this?

**Comment by saystone** [comment]
@superkhau Sorry for the late response. It was resolved. Btw I can't find strongloop documentation for create indexes on MySQL. Where can I find it? (https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Indexes -> still different implemented loopback-connector-mysql code)

**Comment by superkhau** [comment]
@saystone No problem. I'm not sure where it's in the docs, but @crandmck would know.

@crandmck ^

**Comment by crandmck** [comment]
I don't think we have anything specific for creating MySQL indexes.  This is for "auto-migration", right?
We have docs for that: https://docs.strongloop.com/display/LB/Creating+a+database+schema+from+models but nothing specific to MySQL.

Let me know if we need to add something.

**Comment by snowyu** [comment]
the `keys` in the strongloop documentation has still not worked on the mysql connector.

**Comment by crandmck** [comment]
The [comment above](#issuecomment-182803321) says:
>  It was resolved.

Which I thought meant that `keys` now worked on MySQL.  Is that not the case?

**Comment by snowyu** [comment]
No, It DOEST NOT work yet. The only way is a workaround: use the `columns` instead.

**Comment by lotas** [comment]
+1 
Official [Model definition JSON](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file) mention nowhere that there is a `"columns"` property for `"indexes": {}` definition, which is confusing, at least. 

Manually writing `"columns"` works, but is there anywhere documentation for this?

**Comment by crandmck** [comment]
I added this: https://docs.strongloop.com/display/APIC/Model+definition+JSON+file#ModeldefinitionJSONfile-MySQLindexes

Please let me know if I need to add anything more (or change anything).

**Comment by snowyu** [comment]
and should tell people: the `keys` does not work for mysql in the current version.

**Comment by saystone** [comment]
Oh... Sorry for my miss communication. 
I said 'It was resolved'. But I mean it's not for document. It means @wrensburg's solution. 
Ultimately, The document was fixed correctly by @crandmck. But I think some additional comment for document. How can I contribute document?

**Comment by crandmck** [comment]
>How can I contribute document?

@saystone Currently, the best way to contribute is to just suggest changes/additions in a GH issue (i.e. here) and I will make the change.  We're working on getting the docs into a GH repo, but that's going to take quite a bit of time & work :-)

**Comment by buokae** [comment]
I cannot get this to work. I defined 
    "indexes": {
      "RANDOM_UNIQUE_INDEX": {
        "columns": "account,order,filename",
        "kind": "unique"
      }
    },
in my model and on autoupdate I get an error:
ErrorError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order,filename)' at line 1

MySQL 5.7.19, "loopback-connector-mysql": "^5.2.0"
